import type { Product } from '@/types';

/**
 * Fallback products used when the Atlas Core API is unavailable.
 * These mirror the real Robustponds catalog categories:
 * Portas, Complementos, Cortina de Lamelas, Painel, Proteção, Revestimentos Higiénicos
 */
export const FALLBACK_PRODUCTS: Product[] = [
  // ── Portas ──
  { id: 'fp-1', name: 'Porta Frigorífica Deslizante KS 100', slug: 'porta-frigorifica-deslizante-ks-100', description: 'Porta frigorífica deslizante de alto rendimento para câmaras frias industriais.', shortDescription: 'Porta deslizante para câmaras frias', images: [], category: 'Portas', sku: 'BS-KS100', priceEur: 289.90, stock: 15, ref: 'REF001', specs: { 'Tipo': 'Deslizante', 'Largura': '1000 mm', 'Isolamento': 'PU 40mm' } },
  { id: 'fp-2', name: 'Porta Frigorífica Pivotante KP 200', slug: 'porta-frigorifica-pivotante-kp-200', description: 'Porta frigorífica pivotante industrial com dobradiças reforçadas.', shortDescription: 'Porta pivotante industrial', images: [], category: 'Portas', sku: 'BS-KP200', priceEur: 449.00, stock: 8, ref: 'REF002', specs: { 'Tipo': 'Pivotante', 'Largura': '1200 mm', 'Isolamento': 'PU 80mm' } },
  { id: 'fp-3', name: 'Porta Rápida Industrial', slug: 'porta-rapida-industrial', description: 'Porta rápida de abertura automática para tráfego intenso em câmaras frias.', shortDescription: 'Porta rápida automática', images: [], category: 'Portas', sku: 'BS-PRIND', priceEur: 0, stock: undefined, ref: 'REF003', specs: { 'Tipo': 'Rápida', 'Largura': '2000 mm', 'Velocidade': '1 m/s' }, featured: true },
  { id: 'fp-18', name: 'Porta Hospitalar Robustponds', slug: 'porta-hospitalar-robustponds', description: 'Porta frigorífica hospitalar com acabamento higiénico e fechamento hermético.', shortDescription: 'Porta hospitalar higiénica', images: [], category: 'Portas', sku: 'BS-PHOSP', priceEur: 0, stock: undefined, ref: 'REF018', specs: { 'Tipo': 'Hospitalar', 'Acabamento': 'Higiénico', 'Fechamento': 'Hermético' } },

  // ── Complementos ──
  { id: 'fp-4', name: 'Kit Fechadura Industrial KFI', slug: 'kit-fechadura-industrial-kfi', description: 'Kit de fechadura reforçada para portas frigoríficas industriais.', shortDescription: 'Fechadura industrial para portas', images: [], category: 'Complementos', sku: 'BP-KFI', priceEur: 179.90, stock: 20, ref: 'REF004', specs: { 'Material': 'Aço inox', 'Tipo': 'Reforçada' } },
  { id: 'fp-5', name: 'Borracha de Vedação Perimetral', slug: 'borracha-vedacao-perimetral', description: 'Borracha de vedação perimetral para portas e painéis de câmaras frias.', shortDescription: 'Vedação perimetral', images: [], category: 'Complementos', sku: 'BP-VP', priceEur: 259.00, stock: 12, ref: 'REF005', specs: { 'Material': 'EPDM', 'Aplicação': 'Perimetral' } },
  { id: 'fp-6', name: 'Kit Parafusos e Ancoragens ISOFIX', slug: 'kit-parafusos-ancoragens-isofix', description: 'Kit completo de fixação para montagem de painéis isotérmicos.', shortDescription: 'Kit de fixação para painéis', images: [], category: 'Complementos', sku: 'BP-ISOFIX', priceEur: 0, stock: undefined, ref: 'REF006', specs: { 'Material': 'Aço galvanizado', 'Quantidade': '50 peças' } },

  // ── Cortina de Lamelas ──
  { id: 'fp-7', name: 'Cortina de Lamelas PVC Standard', slug: 'cortina-lamelas-pvc-standard', description: 'Cortina de lamelas em PVC para isolamento térmico em câmaras frias.', shortDescription: 'Cortina de lamelas PVC', images: [], category: 'Cortina de Lamelas', sku: 'SP-CLSTD', priceEur: 899.00, stock: 5, ref: 'REF007', specs: { 'Material': 'PVC', 'Espessura': '3 mm', 'Largura': '2000 mm' } },
  { id: 'fp-8', name: 'Cortina de Lamelas Anti-Bactéria', slug: 'cortina-lamelas-anti-bacteria', description: 'Cortina de lamelas com tratamento anti-bacteriano para ambientes sensíveis.', shortDescription: 'Lamelas anti-bacterianas', images: [], category: 'Cortina de Lamelas', sku: 'SP-CLAB', priceEur: 1250.00, stock: 3, ref: 'REF008', specs: { 'Material': 'PVC Anti-Bactéria', 'Espessura': '4 mm', 'Tratamento': 'Anti-Bactéria' } },
  { id: 'fp-9', name: 'Cortina de Lamelas Industrial de Alta Velocidade', slug: 'cortina-lamelas-alta-velocidade', description: 'Cortina de lamelas para zonas de tráfego intenso com sistema de retorno rápido.', shortDescription: 'Lamelas para tráfego intenso', images: [], category: 'Cortina de Lamelas', sku: 'SP-CLAV', priceEur: 0, stock: undefined, ref: 'REF009', specs: { 'Material': 'PVC Reforçado', 'Velocidade': 'Retorno rápido' } },

  // ── Painel ──
  { id: 'fp-10', name: 'Painel Isotérmico PU 80mm', slug: 'painel-isotermico-pu-80mm', description: 'Painel isotérmico em poliuretano de 80mm para construção de câmaras frias.', shortDescription: 'Painel isotérmico PU', images: [], category: 'Painel', sku: 'FT-PU80', priceEur: 129.00, stock: 25, ref: 'REF010', specs: { 'Material': 'PU', 'Espessura': '80 mm', 'Revestimento': 'Chapa zincada' } },
  { id: 'fp-11', name: 'Painel Isotérmico PIR 100mm', slug: 'painel-isotermico-pir-100mm', description: 'Painel com núcleo PIR para isolamento superior e resistência ao fogo.', shortDescription: 'Painel PIR resistente ao fogo', images: [], category: 'Painel', sku: 'FT-PIR100', priceEur: 189.90, stock: 30, ref: 'REF011', specs: { 'Material': 'PIR', 'Espessura': '100 mm', 'Classe Fogo': 'B-s2,d0' } },
  { id: 'fp-12', name: 'Painel Isotérmico Sandwich Personalizado', slug: 'painel-isotermico-sandwich-personalizado', description: 'Painel sandwich isotérmico fabricado à medida para projetos específicos.', shortDescription: 'Painel à medida', images: [], category: 'Painel', sku: 'FT-CUSTOM', priceEur: 0, stock: undefined, ref: 'REF012', specs: { 'Material': 'Sob consulta', 'Personalização': 'Sim' } },

  // ── Proteção ──
  { id: 'fp-13', name: 'Guarda-Rail de Aço Inox', slug: 'guarda-rail-aco-inox', description: 'Guarda-rail de aço inoxidável para proteção de portas e paredes de câmaras frias.', shortDescription: 'Guarda-rail aço inox', images: [], category: 'Proteção', sku: 'AC-GRINOX', priceEur: 12.90, stock: 100, ref: 'REF013', specs: { 'Material': 'Aço inox 304', 'Altura': '150 mm', 'Comprimento': '3000 mm' } },
  { id: 'fp-14', name: 'Cantoneira de Proteção Robusta', slug: 'cantoneira-protecao-robusta', description: 'Cantoneira de proteção para cantos de câmaras frias e corredores.', shortDescription: 'Cantoneira de proteção', images: [], category: 'Proteção', sku: 'AC-CANT', priceEur: 24.90, stock: 50, ref: 'REF014', specs: { 'Material': 'PVC Reforçado', 'Altura': '200 mm', 'Comprimento': '2000 mm' } },
  { id: 'fp-15', name: 'Guarda-Rail Completo Industrial', slug: 'guarda-rail-completo-industrial', description: 'Sistema completo de guarda-rail para proteção perimetral de zonas industriais.', shortDescription: 'Sistema guarda-rail completo', images: [], category: 'Proteção', sku: 'AC-GRCOM', priceEur: 0, stock: undefined, ref: 'REF015', specs: { 'Material': 'Aço inox', 'Tipo': 'Sistema completo' } },

  // ── Revestimentos Higiénicos ──
  { id: 'fp-16', name: 'Revestimento Higiénico Parede Standard', slug: 'revestimento-higienico-parede-standard', description: 'Painel de revestimento higiénico para paredes de câmaras frias e zonas de produção alimentar.', shortDescription: 'Revestimento higiénico para paredes', images: [], category: 'Revestimentos Higiénicos', sku: 'SS-RHSTD', priceEur: 2190.00, stock: 2, ref: 'REF016', specs: { 'Material': 'PVC + GRP', 'Aplicação': 'Paredes', 'Certificação': 'HACCP' } },
  { id: 'fp-17', name: 'Revestimento Higiénico Teto Isotérmico', slug: 'revestimento-higienico-teto-isotermico', description: 'Revestimento higiénico para tetos com isolamento térmico integrado.', shortDescription: 'Revestimento higiénico para tetos', images: [], category: 'Revestimentos Higiénicos', sku: 'SS-RHTETO', priceEur: 0, stock: undefined, ref: 'REF017', specs: { 'Material': 'Sob consulta', 'Aplicação': 'Tetos', 'Isolamento': 'Integrado' } },
  { id: 'fp-19', name: 'Kit Revestimento Higiénico Completo', slug: 'kit-revestimento-higienico-completo', description: 'Kit completo de revestimento higiénico para câmaras frias — paredes e teto.', shortDescription: 'Kit completo de revestimento', images: [], category: 'Revestimentos Higiénicos', sku: 'SS-RHKIT', priceEur: 0, stock: undefined, ref: 'REF019', specs: { 'Material': 'Sob consulta', 'Aplicação': 'Paredes + Tetos' }, featured: true },
];
